### ISSUE TITLE
Review recently added CARTO data

### ISSUE THREAD

**Issue by jcahail** [azavea/mos-energy-benchmark#210]
The Office of Sustainability would like to publish the 2015 data prior to June 30. Please review the data Rupal uploaded and note any changes we need the city to make before publishing.

**Comment by flibbertigibbet** [comment]
We will need the data for 2015 to also be published under https://www.opendataphilly.org/dataset/large-commercial-building-energy-benchmarking so we can add the data download link.

**Comment by flibbertigibbet** [comment]
The data type of the `total_ghg_2015` needs to be changed from `string` to `number`. Apart from that, the new table looks good.

**Comment by flibbertigibbet** [comment]
We now have edit access to the table, so updated the data type myself (didn't see any values that would fail conversion).

**Comment by flibbertigibbet** [comment]
No visualization exists yet that includes 2015, so a new one will need to be created.

**Comment by flibbertigibbet** [comment]
Just noticed an issue with both the old and new data sets @jcahail: there are sector values that differ only by whitespace. So for example, there are rows with 'Retail' as the sector, and other rows with 'Retail ' (with a trailing space) as the sector. That's why the map filter dropdown seems to repeat sector options.

**Comment by flibbertigibbet** [comment]
![image](https://user-images.githubusercontent.com/960264/27402132-9d5fa580-5693-11e7-8f90-59883ffcc48f.png)
